language: go

go:
  - 1.3
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mercurial build-essential xorg-dev libudev-dev libts-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libopenal-dev libogg-dev libvorbis-dev libaudiofile-dev libpng12-dev libfreetype6-dev libusb-dev libdbus-1-dev zlib1g-dev libdirectfb-dev
  - hg clone http://hg.libsdl.org/SDL /tmp/SDL && cd /tmp/SDL && ./configure && make && sudo make install && cd $TRAVIS_BUILD_DIR
  - go get -v github.com/veandco/go-sdl2/sdl

before_script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover
script:
  - go test -covermode=count -coverprofile=coverage.out ./chip8
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -repotoken $COVERALLS_TOKEN